FROM node:alpine as builder
WORKDIR /usr/src/app

RUN node --max-old-space-size=8192 --optimize-for-size

COPY package.json yarn.lock ./

RUN yarn

COPY . .

RUN yarn build

FROM nginx:alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]